-- ========================================
-- DATABASE REBUILD SCRIPT
-- CSE 340 - Assignment 2
-- This file rebuilds the entire database from scratch
-- ========================================

-- ========================================
-- STEP 1: DROP EXISTING STRUCTURES (if any)
-- This ensures a clean rebuild every time
-- ========================================

-- Drop tables first (must drop in order due to foreign key constraints)
DROP TABLE IF EXISTS public.account CASCADE;
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;

-- Drop the type
DROP TYPE IF EXISTS public.account_type CASCADE;

-- ========================================
-- STEP 2: CREATE TYPE
-- ========================================

-- Type: account_type
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

-- Leave owner as default (current user)

-- ========================================
-- STEP 3: CREATE TABLES
-- ========================================

-- Table structure for table `classification`
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pkey PRIMARY KEY (classification_id)
);

-- Table structure for table `inventory`
CREATE TABLE public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING NOT NULL,
    inv_model CHARACTER VARYING NOT NULL,
    inv_year CHARACTER VARYING(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price NUMERIC(9, 0) NOT NULL,
    inv_miles INT NOT NULL,
    inv_color CHARACTER VARYING NOT NULL,
    classification_id INT NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Table structure for table `account`
CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- ========================================
-- STEP 4: CREATE RELATIONSHIPS
-- ========================================

-- Create relationship between classification and inventory tables
ALTER TABLE public.inventory
    ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

-- ========================================
-- STEP 5: INSERT DATA INTO TABLES
-- ========================================

-- Data for table `classification`

INSERT INTO public.classification (classification_name)
VALUES 
    ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

-- Data for table `inventory`

INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
)
VALUES (
    'Chevy',
    'Camaro',
    '2018',
    'If you want to look cool, this is the car you need! This car has great performance at an affordable price. Own it today!',
    '/images/camaro.jpg',
    '/images/camaro-tn.jpg',
    25000,
    101222,
    'Silver',
    2
), (
    'Batmobile',
    'Custom',
    '2007',
    'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to jump from walls and grapple onto building.',
    '/images/batmobile.jpg',
    '/images/batmobile-tn.jpg',
    65000,
    29902,
    'Black',
    1
), (
    'FBI',
    'Surveillance Van',
    '2016',
    'do you like police shows? You will feel right at home driving this van, come complete with surveillance equipments for and extra fee of $2,000 a month. ',
    '/images/fbi-van.jpg',
    '/images/fbi-van-tn.jpg',
    20000,
    19851,
    'Green',
    1
), (
    'Dog',
    'Delorean',
    '1981',
    'Woof woof! this car was featured in back to the future and looks like a dog. Great for people who like to time travel.',
    '/images/delorean.jpg',
    '/images/delorean-tn.jpg',
    40000,
    58001,
    'Silver',
    1
), (
    'Chevy',
    'Suburban',
    '2021',
    'Large spacious SUV able to transport a large family with still plenty of space!',
    '/images/suburban.jpg',
    '/images/suburban-tn.jpg',
    46000,
    14241,
    'Dark Gray',
    3
), (
    'Chevy',
    'Equinox',
    '2019',
    'Sporty and comfortable driving. This is a great vehicle for any adventure.',
    '/images/equinox.jpg',
    '/images/equinox-tn.jpg',
    28000,
    48019,
    'Light Gray',
    3
), (
    'Ford',
    'Ranger',
    '2020',
    'Perfect truck for your construction crew, this truck has great fuel economy as well as a powerful engine that is able to pull heavy loads.',
    '/images/ranger.jpg',
    '/images/ranger-tn.jpg',
    32000,
    33215,
    'Fire Red',
    4
), (
    'Chevy',
    'Silverado',
    '2019',
    'This large truck is the perfect vehicle for driving across Iowa. This truck comes equipt with a large towing package as well.',
    '/images/silverado.jpg',
    '/images/silverado-tn.jpg',
    45000,
    53000,
    'Black',
    4
), (
    'Model',
    'Mini',
    '2017',
    'Mini Cooper Smart Car will give you a great experience of driving an electric car.',
    '/images/mini.jpg',
    '/images/mini-tn.jpg',
    25000,
    26580,
    'Blue',
    5
), (
    'Chevy',
    'Impala',
    '2019',
    'This Impala is a great vehicle for driving, comes complete with great fuel economy as well as a large amount of power under the hood.',
    '/images/impala.jpg',
    '/images/impala-tn.jpg',
    38000,
    10200,
    'Black',
    5
), (
    'Audi',
    'A4',
    '2020',
    'Beat traffic while looking cool by purchasing the new Audi A4.',
    '/images/audi-a4.jpg',
    '/images/audi-a4-tn.jpg',
    42000,
    40001,
    'Dark Gray',
    5
), (
    'Lamborghini',
    'Adventador',
    '2016',
    'Feel like a million bucks by purchasing the Lamborghini Adventador. This car reaches speeds of up to 220 mph.',
    '/images/lambo-Adve.jpg',
    '/images/lambo-Adve-tn.jpg',
    295000,
    25040,
    'Blue',
    2
), (
    'Aston Martin',
    'Vantage',
    '2016',
    'Classy car that makes you stand out from the crowd. This car has great performance and a reliable engine.',
    '/images/aston-vantage.jpg',
    '/images/aston-vantage-tn.jpg',
    120000,
    1000,
    'Silver',
    2
), (
    'Dodge',
    'Challenger',
    '2015',
    'Do you want a car that has large amounts of power? This care is able to go from 0 to 60 MPH in just 3 seconds!',
    '/images/dodge-challenger.jpg',
    '/images/dodge-challenger-tn.jpg',
    35000,
    58914,
    'Black',
    2
), (
    'Jeep',
    'Wrangler',
    '2019',
    'Do you like to go offroading? the Wrangler is the perfect vehicle for all your offroading adventures!',
    '/images/jeep-wrangler.jpg',
    '/images/jeep-wrangler-tn.jpg',
    31000,
    41798,
    'Red',
    3
), (
    'Ford',
    'Flex',
    '2016',
    'Dont let the price tag scare you! this car is a great car for everyday driving',
    '/images/ford-flex.jpg',
    '/images/ford-flex-tn.jpg',
    32000,
    125000,
    'Dark Blue',
    3
), (
    'GM',
    'Hummer',
    '2016',
    'Do you have 6 kids and like to go offroading? The Hummer gives you a huge amount of space and capability, despite its small interiors.',
    '/images/hummer.jpg',
    '/images/hummer-tn.jpg',
    48000,
    65000,
    'Yellow',
    4
), (
    'Hummer',
    'H2',
    '2006',
    'Looking for a truck that makes a statement? The H2 will turn heads wherever you go!',
    '/images/hummer-h2.jpg',
    '/images/hummer-h2-tn.jpg',
    58000,
    85026,
    'Black',
    4
), (
    'GMC',
    'Sierra',
    '2015',
    'Dont have $60,000 to spend on the new model? Buy the 2015 Sierra and get the same great performance.',
    '/images/gmc-sierra.jpg',
    '/images/gmc-sierra-tn.jpg',
    25000,
    158000,
    'White',
    4
), (
    'BMW',
    '3 Series',
    '2019',
    'This is a car that will make all your friends jealous. Dont miss out on driving this car at an affordable price.',
    '/images/bmw-3.jpg',
    '/images/bmw-3-tn.jpg',
    25000,
    48502,
    'Red',
    5
);

-- ========================================
-- UPDATE QUERIES FROM ASSIGNMENT 2
-- These queries modify the data after initial insertion
-- ========================================

-- Query 4: Update "GM Hummer" record - change "small interiors" to "a huge interior"
UPDATE public.inventory
SET inv_description = REPLACE(
    inv_description,
    'small interiors',
    'a huge interior'
)
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Query 6: Update all records in inventory table to add "/vehicles" to file path
UPDATE public.inventory
SET 
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
